modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

issueTrackerURL = "https://github.com/Team-Resourceful/Resourceful-Config/issues"

[[mods]]
    modId = "resourcefulconfig"
    version = "${version}"
    displayName = "Resourcefulconfig"
    logoFile = "icon.png"
    description = "A library for creating config files for your mod across multiple platforms."

[[mixins]]
    config = "resourcefulconfig.mixins.json"

[[dependencies.resourcefulconfig]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.5,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.resourcefulconfig]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.5,)"
    ordering = "NONE"
    side = "BOTH"
